version: "3.9"


services:

  # -------------------------------
  # Correo API
  # -------------------------------

  correo_api:
    build: ./Correo
    container_name: correo_api
    restart: always
    ports:
      - "8002:8000"
    volumes:
      - ./Correo/app:/app/app 
    networks:
      - basic

  
  # -------------------------------
  # Postgres Database
  # -------------------------------
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: votaciones_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"   # solo si quieres acceder desde tu PC
    networks:
      - basic

  # -------------------------------
  # APISIX Gateway
  # -------------------------------
  apisix:
    image: apache/apisix:latest

    depends_on:
      - backend-crud
      # - vote
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml
    ports:
      - "80:9080"
    networks:
      - basic

  # -------------------------------
  # Backend de Crud (Auth)
  # -------------------------------
  backend-crud:
    build: ./backend-crud
    container_name: backend-crud
    env_file:
      - ./backend-crud/.env
    networks:
      - basic
    depends_on:
      - postgres
    ports:
      - "4000:4000"

  # -------------------------------
  # Backend Go (Lógica)
  # -------------------------------
  # vote:
  #   build:
  #     context: ./vote            # <--- Ruta a la carpeta vote/
  #   env_file:
  #     - ./vote/.env
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - basic

# -------------------------------
# Volúmenes y redes
# -------------------------------
volumes:
  postgres_data:

networks:
  basic:
    driver: bridge
