version: "3.9"

services:
  correo_api:
    build: .
    container_name: correo_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app   # Permite editar sin reconstruir
    environment:
      - TZ=America/Bogota
