services:
  some-postgres:
    image: postgres:17
    container_name: some-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: votaciones_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - basic

  

volumes:
  postgres_data:

networks:
  basic:
    driver: bridge